server:
  port: 8081

spring:
  application:
    name: ms-customer
  datasource:
    #Configs para o docker compose
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-customer
    username: postgres
    password: suasenha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#feign:
#  product:
#    url: http://localhost:8082/api/v1/product

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #Config para o docker compose
      #defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      defaultZone: http://localhost:8761/eureka/